### ISSUE TITLE
Feature request: support for french language

### ISSUE THREAD

**Issue by Quezako** [mentegago/streamkit#2]
Hello,

I've searched a lot of TTS apps to speech my chat, but I can't find one that supports both japanese and french.
Do you think that you can add french support?
Something like: if there are kanji or hiragana, speak japanese, else speak french.

Thanks in advance for your help

**Comment by mentegago** [comment]
Yup, I can do that.
~~However, I'll need to train StreamKit to understand French Twitch chat pattern, so can you help recommend channels where most (or even better, all of the chats) are in French? Preferably not too big, but not to small either (10-100 viewers?).~~

Never mind, I found a good enough training data. I'll be releasing it pretty soon.

Thanks.

**Comment by Quezako** [comment]
Ok great! Thanks a lot!

**Comment by mentegago** [comment]
French language is now implemented on [StreamKit 0.5](https://github.com/mentegago/streamkit/releases/latest). Enjoy @Quezako.

**Comment by Quezako** [comment]
Thanks a lot! It works great! :)
