### ISSUE TITLE
[BUG] App wont start on Windows 11 22H2

### ISSUE THREAD

**Issue by bagusnl** [mentegago/streamkit#5]
Currently on the Windows 11 Insider RP 22H2 Build 22621.105. Streamkit wont start after opening it.
Current workaround is to put it on compatibility mode set to Windows 8.

Can't see any way to collect crash log, will include some Event Viewers logs instead below.

Behavior without compatibility mode: After opening StreamKit, it opens 2 streamkit.exe process with one of them being suspended. Both of them only loads about 50K on RAM. Both process would crash about 5 seconds after launching.

Behavior with compatibility mode: App started instantly and working normally with only 1 process running.

Event Viewer Logs:

1st process:
APPCRASH
```
Faulting application name: streamkit.exe, version: 0.5.1.0, time stamp: 0x628e41c5
Faulting module name: streamkit.exe, version: 0.5.1.0, time stamp: 0x628e41c5
Exception code: 0xc0000005
Fault offset: 0x0000000000005670
Faulting process id: 0x0xC70
Faulting application start time: 0x0x1D8899868DB9FDC
Faulting application path: C:\Program Files\Mentega StreamKit\Chat Reader\streamkit.exe
Faulting module path: C:\Program Files\Mentega StreamKit\Chat Reader\streamkit.exe
Report Id: 6bbd37e7-3501-4ea9-b141-fc6db31da458
Faulting package full name: 
Faulting package-relative application ID: 
```
WER
```
Fault bucket 1550453849937743381, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: streamkit.exe
P2: 0.5.1.0
P3: 628e41c5
P4: streamkit.exe
P5: 0.5.1.0
P6: 628e41c5
P7: c0000005
P8: 0000000000005670
P9: 
P10: 
```

2nd process:
APPCRASH
```
Faulting application name: streamkit.exe, version: 0.5.1.0, time stamp: 0x628e41c5
Faulting module name: streamkit.exe, version: 0.5.1.0, time stamp: 0x628e41c5
Exception code: 0xc000041d
Fault offset: 0x0000000000005670
Faulting process id: 0x0xC70
Faulting application start time: 0x0x1D8899868DB9FDC
Faulting application path: C:\Program Files\Mentega StreamKit\Chat Reader\streamkit.exe
Faulting module path: C:\Program Files\Mentega StreamKit\Chat Reader\streamkit.exe
Report Id: 9996e1fd-de16-4a1c-889f-c7e5e1980d84
Faulting package full name: 
Faulting package-relative application ID: 
```
WER
```
Fault bucket 1714381908163466492, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: streamkit.exe
P2: 0.5.1.0
P3: 628e41c5
P4: streamkit.exe
P5: 0.5.1.0
P6: 628e41c5
P7: c000041d
P8: 0000000000005670
P9: 
P10: 
```

**Comment by mentegago** [comment]
I'm not currently on Windows 11, so still can't check.
In the mean time, I'll be watching if there are related issues on Flutter or any of the libraries to see what's wrong.

**Comment by redsolver** [comment]
I had the same issue with an app I'm building, so I guess it's https://github.com/bitsdojo/bitsdojo_window/issues/59 because you're using the library too

**Comment by mentegago** [comment]
I'm currently on W11 21H2 and the issue doesn't happen.
I think I'll wait for stable release of 22H2 until I start debugging this.

**Comment by bagusnl** [comment]
Well, idk if it still happen in regular 22H2 but I'm on 22H2 Insider Dev (25193.1000) and its not happening anymore (v 0.6) ... 
Kinda weird

Edit: even 0.5.1_hotfix works in newest build

**Comment by mentegago** [comment]
Hmm, seems like an issue in Windows, I guess?
I'll close it for now and reopen if the stable 22H2 has the same issue.
Thanks for the report.

**Comment by mentegago** [comment]
Seems like stable _does_ have the issue. Reopening.
